language: python
matrix:
  include:
  - python: 3.5-dev
    env: TOXENV=py35,coveralls
  - python: 3.4
    env: TOXENV=py34
  - python: 3.3
    env: TOXENV=py33
  - python: 2.7
    env: TOXENV=py27,coveralls
  - python: 2.6
    env: TOXENV=py26
  - python: pypy3
    env: TOXENV=pypy3
  - python: pypy
    env: TOXENV=pypy
install: pip install tox
script: tox
deploy:
  provider: pypi
  user: {{ cookiecutter.pypi_username }}
  password: TODO
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: $TRAVIS_JOB_NUMBER = *.1
