language: python

python:
  - '3.5'

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy3
  - TOXENV=pypy

install:
  - pip install cookiecutter
  - pip install tox

script:
  - cookiecutter . --no-input
  - cd ./python_boilerplate
  - tox
